// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inyyfwqfdpidnacertuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueXlmd3FmZHBpZG5hY2VydHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTQyODcsImV4cCI6MjA3MjYzMDI4N30.DHdNterfRfxyp61hNU9_JjTUM2ngVHDTEAhVaE2wr-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});